name: install

on:
  push:
    tags:
      - "v*"
    branches:
      - "**"
    paths:
      - ".github/workflows/install.yml"
      - "assets/**"
      - "**.py"
  pull_request:
    branches:
      - "**"
    paths:
      - ".github/workflows/install.yml"
      - "assets/**"
      - "**.py"
  workflow_dispatch:

jobs:
  meta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: set_tag
        run: |
          is_release=${{ startsWith(github.ref, 'refs/tags/v') }}
          tag=$(git describe --tags --match "v*" ${{ github.ref }} || true)
          if [[ $tag != v* ]]; then
            tag=$(curl -sX GET "https://api.github.com/repos/${{ github.repository }}/releases/latest" --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | awk '/tag_name/{print $4}' FS='["]')
            if [[ $tag != v* ]]; then
              tag="v0.0.0"
            fi
            tag=$(date "+$tag-%y%m%d-$(git rev-parse --short HEAD)")
          fi
          if ! $($is_release) ; then
            prefix=${tag%-*-*}
            suffix=${tag#$prefix-}
            tag="$prefix-ci.$suffix"
          fi

          echo tag=$tag | tee -a $GITHUB_OUTPUT
          echo is_release=$is_release | tee -a $GITHUB_OUTPUT
    outputs:
      tag: ${{ steps.set_tag.outputs.tag }}
      is_release: ${{ steps.set_tag.outputs.is_release }}

  windows:
    needs: meta
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [aarch64, x86_64]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Download MaaFramework
        uses: robinraju/release-downloader@v1
        with:
          repository: MaaXYZ/MaaFramework
          fileName: "MAA-win-${{ matrix.arch }}*"
          latest: true
          out-file-path: "deps"
          extract: true

      - name: Download MFAWPF  
        uses: robinraju/release-downloader@v1  
        with:
          repository: SweetSmellFox/MFAWPF
          fileName: "MFAWPF*"
          latest: true
          out-file-path: "MFA"
          extract: true

      - name: Install
        shell: bash
        run: |
          python ./install.py ${{ needs.meta.outputs.tag }}
          cp MFA/MFAWPF.exe install

      - uses: actions/upload-artifact@v4
        with:
          name: MAAIP-win-${{ matrix.arch }}
          path: "install"


  release:
    if: ${{ needs.meta.outputs.is_release == 'true' }}
    needs: [meta, windows, ubuntu, macos, android]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: assets

      - name: Check assets directory
        run: |
          ls -la assets
          if [ -z "$(ls -A assets)" ]; then
            echo "assets directory is empty"
            exit 1
          fi

      - name: Compress and generate checksums
        run: |
          cd assets
          echo "Generating checksums for all zip files..."
          checksum_file="checksums.txt"
          touch "$checksum_file"
      
          for f in *; do
            if [ -d "$f" ]; then
              echo "Processing directory: $f"
              zip_file="$f-${{ needs.meta.outputs.tag }}.zip"
              (cd "$f" && zip -r "../$zip_file" .)
              if [ $? -eq 0 ]; then
                echo "ZIP file created: ../$zip_file"
                echo "Processing directory: $f"
                sha256sum "$zip_file" >> "$checksum_file"
                echo "" >> "$checksum_file"
              else
                echo "Failed to create ZIP file: ../$zip_file"
                exit 1
              fi
            else
              echo "Skipping non-directory: $f"
            fi
          done

      - uses: softprops/action-gh-release@v2
        with:
          files: assets/*
          tag_name: ${{ needs.meta.outputs.tag }}

      - name: Trigger MirrorChyanUploading
        run: |
          gh workflow run --repo $GITHUB_REPOSITORY mirrorchyan
          gh workflow run --repo $GITHUB_REPOSITORY mirrorchyan_release_note
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
