name: mirrorchyan

on:
  workflow_dispatch:

jobs:
  mirrorchyan:
    runs-on: macos-latest
    steps:
      - id: uploading
        uses: MirrorChyan/uploading-action@v1
        with:
          filetype: latest-release
          filename: "MaaIP-win-x86_64-*.zip"
          pick_files: '["resource", "interface.json"]'
          exclude_files: '["*model/ocr/**"]'
          mirrorchyan_rid: MAAIP

          owner: Arcelibs
          repo: MAAIP
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
